version: "3.8"

services:
  db:
    image: db
    restart: on-failure
    container_name: db
    build:
      context: ./scripts/postgres
      target: db
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  pgdata:
    driver: local